# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  ':bug: bug':
    include:
      - '\bbug(?=:)'
  ':star2: feature':
    include:
      - '\bfeature(?=:)'
  ':blue_book: documentation':
    include:
      - '\bdocs(?=:)'
  ':broom: chore':
    include:
      - '\bchore(?=:)'
  ':framed_picture: design':
    include:
      - '\bdesign(?=:)'
  ':test_tube: test':
    include:
      - '\btest(?=:)'
  ':toolbox: refactor':
    include:
      - '\brefactor(?=:)'
  ':package: ci/cd':
    include: ['\bci/cd(?=:)', '\bci(?=:)', '\bcd(?=:)']
