import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import './globals.css';
import { ToggleButton } from '@/components/ToggleButton';
import { getCurrentScheme } from '@/utils/colorScheme';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const scheme = await getCurrentScheme();

  return (
    <html lang='ko' className={scheme === 'dark' ? 'dark' : ''}>
      <body className={inter.className}>
        <ToggleButton />
        {children}
      </body>
    </html>
  );
}
